#baseURL = 'http://example.org/'
#languageCode = 'en-us'
#title = 'My Ramblings on Tech'
#theme = "blackburn"
#
#enableRobotsTXT = true
#
#[params]
#  text_color = ""
#  author = ""
#  favicon = ""
#  site_logo = ""
#  description = "The last theme you'll ever need. Maybe."
#  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#  background_color_class = "bg-black"
#  recent_posts_number = 3
#
#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"
#
#[menu]
#[[menu.main]]
#  identifier = 'resume'
#  name = 'resume'
#  pre = "<i class='fa fa-heart'></i>"
#  url = '/resume/'
#  weight = -110
#[[menu.main]]
#  name = 'getting started'
#  post = "<span class='alert'>New!</span>"
#  pre = "<i class='fa fa-road'></i>"
#  url = '/getting-started/'
#  weight = -100

baseurl = "https://www.example.com/" # Make sure to end baseurl with a '/'
#title = "Your site title"
author = "Your name"
# Shown in the side menu
copyright = "&copy; 2022. All rights reserved."
canonifyurls = true
paginate = 10
theme = "blackburn"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  #subtitle = "A Hugo Theme"
  brand = "BK"
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

  #[params.piwikAnalytics]
  #  siteid = 2
  #  piwikroot = "//analytics.example.com/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-file fa-fw'></i>"
    weight = 3
    identifier = "resume"
    url = "/resume/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"
  #[[menu.main]]
  #  name = "Contact"
  #  pre = "<i class='fa fa-phone fa-fw'></i>"
  #  weight = 4
  #  url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  #twitter = "*"
  #gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  #facebook = "*"
  #googleplus = "*"
  #weibo = "*"
  #tumblr = "*"

  # SNS photo/video sharing
  #instagram = "*"
  #flickr = "*"
  #photo500px = "*"
  #pinterest = "*"
  #youtube = "*"
  #vimeo = "*"
  #vine = "*"
  #slideshare = "*"

  # SNS career oriented
  linkedin = "bkonicek"
  #xing = "*"

  # SNS news
  #reddit = "*"
  #hackernews = "*"

  # Techie
  github = "bkonicek"
  #gitlab = "*"
  #bitbucket = "*"
  #stackoverflow = "*"
  #serverfault = "*"

  # Gaming
  #steam = "speel_my_drink"
  #mobygames = "*"

  # Music
  #lastfm = "*"
  #discogs = "*"

  # Other
  #keybase = "*"